### ISSUE TITLE
Update to DIN 5008:2020

### ISSUE THREAD

**Issue by maxwxyz** [bertramrichter/LaTeX_Briefvorlage#5]
Is it possible to make an option for the current standard DIN 5008:2020 (letter versions A and B)?
The standard changed quite significantly the structure of the template, especially the address field and additional fields (date, references, phone/web/email) all on the top right side now.

**Comment by bertramrichter** [comment]
Thanks for the interest and the notification.
It would be certainly possible to do, but the class is currently not designed for this purpose (really limited use case).
When creating, I only implemented the A version and didn't intend to support the B at all.

I might take a look into the new standard, when I have time and muse to (but I can't say, when this will be).

**Comment by bertramrichter** [comment]
After skimming over the new norm, version A and B seem to differ only in a few length (notably, the header), so supporting both seems like a reasonable thing to do.

Marked for the next release.

**Comment by bertramrichter** [comment]
I took the weekend and made a new release `v0.4`.
If this satisfies your needs, you might close this issue.
I'm pleased to know someone else than me using it. :smiley: 

Thank you for the kind push.

**Comment by maxwxyz** [comment]
Thanks!
